name: asv-mdanalysis-benchmark
channels:
  - conda-forge
dependencies:
  - cython>=0.28
  - pip
  - python-build
  - wheel
  - dask>=2023.1.1
  - filelock
  - griddataformats>=0.4.0
  - gsd>3.0.0
  - h5py>2.1.0
  - joblib>=0.12
  - matplotlib-base>=1.5.1
  - mda-xdrlib
  - mmtf-python>=1.0.0
  - netcdf4
  - numpy>=1.23.2
  - packaging
  - pandas
  - pyedr>0.7.0
  - pytng>=0.2.3
  - scikit-learn
  - scipy>=1.5.0
  - seaborn>=0.7.0
  - setuptools
  - threadpoolctl
  - tidynamics>1.0.0
  - tqdm>=4.43.0
  - biopython>=1.80
  - chemfiles>=0.10
  - distopia>=0.3.0
